runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /imgs
  static_dir: imgs
- url: /style
  static_dir: style
- url: /.*
  script: dorm.app

libraries:
  - name: jinja2
    version: latest
